### ISSUE TITLE
Change database from default SQLite to Postgres

### ISSUE THREAD

**Issue by GitRepsOfficial** [GitRepsCommunity/platform#1]
_Instructions written by ChatGPT!_

Step 1: Install PostgreSQL
If you haven't already, you'll need to install PostgreSQL on your development machine. You can download and install it from the official PostgreSQL website: https://www.postgresql.org/download/

Step 2: Install the pg gem
In order to use PostgreSQL with Ruby on Rails, you need to have the pg gem installed. This gem provides the necessary PostgreSQL adapter for Rails. Open your Gemfile, which is located in the root directory of your Rails app, and add the following line:

```ruby
gem 'pg'
```

Save the Gemfile and then run `bundle install` in your terminal to install the pg gem.

Step 3: Configure database.yml
Next, you need to configure your database.yml file to use PostgreSQL. This file is also located in the root directory of your Rails app and contains the database configuration settings. Open database.yml and modify the development section to use PostgreSQL like this:

```ruby
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_postgres_username
  password: your_postgres_password # If you set one during PostgreSQL installation

development:
  <<: *default
  database: your_app_name_development

```

Make sure to replace `your_postgres_username`, `your_postgres_password`, `your_app_name`, and other configuration values with your actual PostgreSQL settings.

Step 4: Create and Migrate the Database
After updating database.yml, you'll need to create and migrate your database. Run the following commands in your terminal:

```ruby
rails db:create # This will create the databases
rails db:migrate # This will run any pending migrations
```

Step 5: Verify and Test
At this point, your Rails app should be using PostgreSQL as the database. You can run your app in development mode and test it to make sure everything is working as expected.

Remember to restart your Rails server (`rails server`) after making these changes to the database.yml file.

**Comment by andrewjumanca** [comment]
For the Postgres username and password, should I set up a new login or do we have an existing login intended for this project?

**Comment by GitRepsOfficial** [comment]
For local development, I usually just use `postgres` as both the username and password. When we're ready to deploy and use a hosted database, we'll get the credentials for that instance and use environment variables to manage them.
