### ISSUE TITLE
Update README with instructions for local development

### ISSUE THREAD

**Issue by GitRepsOfficial** [GitRepsCommunity/platform#6]
Update details in the project readme: https://github.com/GitRepsCommunity/platform/blob/main/README.md

Make sure to include dev environment setup steps:

* Install ruby environment manager: https://github.com/rbenv/rbenv
* Install ruby version: https://github.com/GitRepsCommunity/platform/blob/main/.ruby-version
* Install postgres: https://postgresapp.com/
* Clone the repo: https://github.com/GitRepsCommunity/platform.git

**Comment by GitRepsOfficial** [comment]
@andrewjumanca Try getting your environment setup so that you can start the server locally (see: https://guides.rubyonrails.org/command_line.html#bin-rails-server). Pay attention to anywhere you get blocked so we can add troubleshooting notes to the README. Let me know if you get stuck and I'll help you work through it.

**Comment by andrewjumanca** [comment]
I've added the basic installation instructions to the README to get the server running locally.
