### ISSUE TITLE
Add Sign Out link to navigation

### ISSUE THREAD

**Issue by GitRepsOfficial** [GitRepsCommunity/platform#66]
Add the following condition to `app/views/shared/_nav.html.erb`.

```ruby
<%- if user_signed_in? %>
    <%= button_to "Log out", destroy_session_path(resource_name), method: :delete %>
```

Make sure to use `button_to` based on this [issue](https://github.com/heartcombo/devise/issues/4486#issuecomment-444534885).

**Comment by andrewjumanca** [comment]
@GitRepsOfficial I may be wrong but part of this seems to be blocked at least partly by issue #64 since @ahmedg10 is changing the email / password login page (because we don't need anything except Github auth). Should I wait for that to be merged before pushing anything to this issue?

**Comment by GitRepsOfficial** [comment]
@andrewjumanca It should be fine to work on this before #64 is merged since there's no technical dependency on it.
